# Strings


eng_loc = {
    'Main Device':          'Primary Device',
    'Board HW ID':          'Board HW ID',
    'Board Serial':         'Board Serial',
    'App Build Timestamp':  'App Build Timestamp',
    'App Build Date':       'App Build Date',
    'BL Build Timestamp':   'BL Build Timestamp',
    'BL Build Date':        'BL Build Date',

    'Secondary Device':     'Secondary Device',

    'Status':               'Status',
    'Packet Number':        'Packet Number',
    'Missed Packets':       'Missed Packets',
    'Avg. Missed/s':        'Avg. Missed/s',
    'Frame Rate':           'Frame Rate',

    'Trackpad':             'Trackpad',
    'X Left':               'X Left',
    'Y Left':               'Y Left',
    'X Right':              'X Right',
    'Y Right':              'Y Right',
    'Pressure Left':        'Pressure Left',
    'Pressure Right':       'Pressure Right',
    'Finger Present L':     'Finger Present L',
    'Finger Present R':     'Finger Present R',
    'Click Left':           'Click Left',
    'Click Right':          'Click Right',

    'Trackpad Plots':       'Trackpad Plots',
    'Left':                 'Left',
    'Right':                'Right',

    'Thumbsticks':          'Thumbsticks',
    'Thumbstick Plots':     'Thumbstick Plots',
                         
    'L Stick X':            'L Stick X',     
    'L Stick Y':            'L Stick Y',
    'R Stick X':            'R Stick X',
    'R Stick Y':            'R Stick Y',
    'L Stick Raw':          'L Stick Raw',
    'L Stick Touch':        'L Stick Touch',
    'L Stick Click':        'L Stick Click',
    'R Stick Raw':          'R Stick Raw',
    'R Stick Touch':        'R Stick Touch',
    'R Stick Click':        'R Stick Click',

    'Analog Triggers':      'Analog Triggers',
    'trigger raw_left':     'trigger raw_left',
    'trigger left button':  'trigger left button',
    'trigger raw_right':    'trigger raw_right',
    'trigger right button': 'trigger right button',
    'trigger threshold':    'trigger threshold',
    'bumper left button':   'bumper left button',
    'bumper right button':  'bumper right button',

    'Accel/Gyro':           'Accel/Gyro',
    'Accel X':              'Accel X',
    'Accel Y':              'Accel Y',
    'Accel Z':              'Accel Z',
    'Gyro X':               'Gyro X',
    'Gyro Y':               'Gyro Y',
    'Gyro Z':               'Gyro Z',

    'Orientation':          'Orientation',
    'Quat W':               'Quat W',
    'Quat X':               'Quat X',
    'Quat Y':               'Quat Y',
    'Quat Z':               'Quat Z',
    'Pitch':                'Pitch',
    'Roll':                 'Roll',
    'Yaw':                  'Yaw',

    'Haptic':               'Haptic',
    'Haptics Enabled':      'Haptics Enabled',
    'Haptics On  usec':     'Haptics On  usec',
    'Haptics Off usec':     'Haptics Off usec',
    'Haptics Repeat Count': 'Haptics Repeat Count',
    'Haptics Loop Time':    'Haptics Loop Time',
    'Haptic Mode':          'Haptic Mode',

    'Left Buttons':         'Left Buttons',
    'up':                   'up',
    'right':                'right',
    'left':                 'left',
    'down':                 'down',
    'select':               'select',
    'steam':                'steam',

    'Right Buttons':        'Right Buttons',
    'y':                    'y',
    'b':                    'b',
    'x':                    'x',
    'a':                    'a',
    'start':                'start',
    'Alt':                  'Alt',

    'Grip Buttons':         'Grip Buttons',
    'Grip L Upper':         'Grip L Upper',
    'Grip L Lower':         'Grip L Lower',
    'Grip R Upper':         'Grip R Upper',
    'Grip R Lower':         'Grip R Lower',

    'Device Control':       'Device Control',
    'Device Number':        'Device Number',
    'Logging Enabled':      'Logging Enabled',
    'Log Compression':      'Log Compression',
    'Raw Trackpad Data':    'Raw Trackpad Data',
    'Debug Mode':           'Debug Mode',

    'Trackpad Config':      'Trackpad Config',
    'Trackpad Z Thresh':    'Trackpad Z Thresh',
    'Trackpad Cent Thresh': 'Trackpad Cent Thresh',
    'Trackpad Clip':        'Trackpad Clip',
    'Trackpad Sensor Filt': 'Trackpad Sensor Filt',
    'Trackpad Hyst':        'Trackpad Hyst',
    'Trackpad Experimental': 'Trackpad Experimental',
    'Trackpad Centroid Filt': 'Trackpad Centroid Filt',
    'Gate Mode':            'Gate Mode',

    'Calibration State':    'Calibration State',
    'Thumbsticks':          'Thumbsticks',
    'Triggers':             'Triggers',
    'Pressure':             'Pressure',

}

chi_loc = {
    'Main Device':          '主设备',
    'Board HW ID':          '电路板硬件ID',
    'Board Serial':         '电路板序列号',
    'App Build Timestamp':  'APP发布时间标记',
    'App Build Date':       'APP发布时间',
    'BL Build Timestamp':   '引导加载程序发布时间标记',
    'BL Build Date':        '引导加载程序发布时间',

    'Secondary Device':     '从设备',

    'Status':               '状态',
    'Packet Number':        '数据包数量',
    'Missed Packets':       '丢失数据包数量',
    'Avg. Missed/s':        '平均数据包丢失率',
    'Frame Rate':           '帧刷新率',

    'Trackpad':             '触摸板',
    'X Left':               '触摸板X轴左边',
    'Y Left':               '触摸板Y轴左边',
    'X Right':              '触摸板X轴右边',
    'Y Right':              '触摸板Y轴右边',
    'Pressure Left':        '左边压力',
    'Pressure Right':       '右边压力',
    'Finger Present L':     '左边手指检测',
    'Finger Present R':     '右边手指坚持',
    'Click Left':           '左边单击',
    'Click Right':          '右边单击',

    'Trackpad Plots':       '触摸板图形',
    'Left':                 '左边',
    'Right':                '右边',

    'Thumbsticks':          '摇杆',
    'Thumbstick Plots':     '摇杆图形',

    'L Stick X':            '摇杆X轴左边',     
    'L Stick Y':            '摇杆Y轴左边',
    'R Stick X':            '摇杆X轴右边',
    'R Stick Y':            '摇杆Y轴右边',
    'L Stick Raw':          '摇杆左边数据',
    'L Stick Touch':        '摇杆左边触摸',
    'L Stick Click':        '摇杆左边单击',
    'R Stick Raw':          '摇杆右边数据',
    'R Stick Touch':        '摇杆右边触摸',
    'R Stick Click':        '摇杆右边单击',

    'Analog Triggers':      '模拟扳机',
    'trigger raw_left':     '左扳机数据',
    'trigger left button':  '左扳机键',
    'trigger raw_right':    '右扳机数据',
    'trigger right button': '右扳机键',
    'trigger threshold':    '扳机阀值',
    'bumper left button':   'Bumper左键',
    'bumper right button':  'Bumper右键',

    'Accel/Gyro':           '加速度计/陀螺仪',
    'Accel X':              '加速度X轴',
    'Accel Y':              '加速度Y轴',
    'Accel Z':              '加速度Z轴',
    'Gyro X':               '陀螺仪X轴',
    'Gyro Y':               '陀螺仪Y轴',
    'Gyro Z':               '陀螺仪Z轴',

    'Orientation':          '方向',
    'Quat W':               '陀螺仪四元数_W',
    'Quat X':               '陀螺仪四元数_X',
    'Quat Y':               '陀螺仪四元数_Y',
    'Quat Z':               '陀螺仪四元数_Z',
    'Pitch':                '俯仰角θ',
    'Roll':                 '滚转角Φ',
    'Yaw':                  '偏航角ψ',

    'Haptic':               '触感',
    'Haptics Enabled':      '触感使能',
    'Haptics On  usec':     '触感开时间(us)',
    'Haptics Off usec':     '触感关时间(us)',
    'Haptics Repeat Count': '触感重复次数',
    'Haptics Loop Time':    '触感持续时间',
    'Haptic Mode':          '触感模式',

    'Left Buttons':         '左边按键',
    'up':                   '上键',
    'right':                '右键',
    'left':                 '左键',
    'down':                 '下键',
    'select':               '选择键',
    'steam':                'steam键',

    'Right Buttons':        '右边按键',
    'y':                    'y键',
    'b':                    'B键',
    'x':                    'X键',
    'a':                    'A键',
    'start':                'start键',
    'Alt':                  'alt键',

    'Grip Buttons':         'Grip键',
    'Grip L Upper':         '左边Grip上键',
    'Grip L Lower':         '左边Grip下键',
    'Grip R Upper':         '右边Grip上键',
    'Grip R Lower':         '右边Grip下键',

    'Device Control':       '设备控制',
    'Device Number':        '设备数量',
    'Logging Enabled':      '数据使能',
    'Log Compression':      '数据压缩',
    'Raw Trackpad Data':    'Raw Trackpad Data',
    'Debug Mode':           '调试模式',

    'Trackpad Config':      '触摸板配置',
    'Trackpad Z Thresh':    '触摸板Z阀值',
    'Trackpad Cent Thresh': '触摸板中心阀值',
    'Trackpad Clip':        '触摸板 clip',
    'Trackpad Sensor Filt':   '触摸板IIR 滤波器',
    'Trackpad Hyst':        '触摸板迟滞',
    'Trackpad Experimental': 'Trackpad Experimental',
    'Trackpad Centroid Filt': 'Trackpad Centroid Filt',
    'Gate Mode':            'Gate Mode',


    'Calibration State':    '触摸板状态',
    'Thumbsticks':          '摇杆',
    'Triggers':             '扳机键',
    'Pressure':             '压力',
}






loc_strings = {
    "eng": eng_loc,
    "chi": chi_loc,
}